[project]
name = "finetuningqwen30-6b"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "XianYuSenior", email = "1148656615@qq.com" }
]
requires-python = ">=3.14"
dependencies = [
    "accelerate>=1.15.0",
    "datasets>=4.7.0",
    "matplotlib>=3.11.2",
    "peft>=0.21.0",
    "tensorboard>=2.21.0",
    "torch>=2.14.0",
    "torchvision>=0.29.0",
    "transformers>=5.17.0",
    "trl>=1.13.0",
]

[project.scripts]
finetuningqwen30-6b = "finetuningqwen30_6b:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/cu130"
name = "pytorch-cu130"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu130" }
torchvision = { index = "pytorch-cu130" }
